# Generated by Django 4.0 on 2022-04-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_img', models.ImageField(blank=True, null=True, upload_to='teacher_images')),
                ('teacher_name', models.CharField(max_length=120)),
                ('teacher_skill', models.CharField(max_length=120)),
                ('teacher_desc', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=2000, null=True)),
                ('facebook', models.CharField(blank=True, max_length=2000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_img', models.ImageField(blank=True, null=True, upload_to='courses_images')),
                ('select_category', models.CharField(choices=[('Web Development', 'Web Development'), ('Digital Marketting', 'Digital Marketing'), ('Word Press', 'Word Press'), ('Amazon', 'Amazon'), ('Programming', 'Programming'), ('Diploma', 'Diploma'), ('Short Course', 'Short Course')], max_length=20)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(max_length=120)),
                ('course_desc', models.TextField()),
                ('seats', models.IntegerField(blank=True, default=40, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('select_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.add_teacher')),
            ],
        ),
    ]
