# Generated by Django 4.0 on 2022-04-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=40, null=True)),
                ('birth_date', models.DateField()),
                ('select_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('select_domicile', models.CharField(choices=[('Mohmand', 'Mohmand'), ('Peshawar', 'Peshawar'), ('Charsadda', 'Charsadda')], max_length=10)),
                ('mobile_no', models.IntegerField(blank=True, null=True)),
                ('cnic', models.IntegerField(blank=True, null=True)),
                ('guardian_no', models.IntegerField(blank=True, null=True)),
                ('select_qualification', models.CharField(choices=[('Matriculation', 'Matriculation'), ('FSC', 'FSC'), ('Bachelor', 'Bachelor'), ('Master', 'Master')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('Address', models.TextField()),
                ('select_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.add_course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
