# Generated by Django 4.0 on 2022-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_apply_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_course',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents'),
        ),
        migrations.AddField(
            model_name='apply_course',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents'),
        ),
        migrations.AddField(
            model_name='apply_course',
            name='fsc_dmc',
            field=models.FileField(blank=True, null=True, upload_to='media/documents'),
        ),
        migrations.AddField(
            model_name='apply_course',
            name='matric_dmc',
            field=models.FileField(blank=True, null=True, upload_to='media/documents'),
        ),
        migrations.AddField(
            model_name='apply_course',
            name='select_img',
            field=models.ImageField(default=1, upload_to='media/profile'),
            preserve_default=False,
        ),
    ]
