# Generated by Django 4.0 on 2022-04-06 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('academy', '0004_rename_user_apply_course_select_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_course',
            name='select_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
